services:
  web:
    build: .
    container_name: mysite-web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123123123

  db:
    image: postgres
    container_name: mysite-db
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: